CREATE TABLE GAESTEBUCH(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), TEXT VARCHAR(255));
INSERT INTO GAESTEBUCH(NAME, TEXT) VALUES('Valentin','Hallo blablabla');
SELECT * FROM GAESTEBUCH
DELETE FROM GAESTEBUCH WHERE NAME='Valentin';